name: Bug Report
description: Create a new bug report.
title: "[BUG] New Bug"
labels: [bug]
body:
  - type: textarea
    id: issue
    attributes:
      label: Bug/Issue
      description: What is the bug or issue?
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: Debug Log Message
      description: Set the `LOG_LEVEL` envrionment variable to `DEBUG` and paste the entire log message.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Information
      description: Provide any other information or context that may be relevant to the bug and/or steps that can possibly reproduce the bug.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Code Changes
      description: Provide code changes for the feature if you have any. Use comments to specify files or context.
    validations:
      required: false