name: Feature Suggestion
description: Suggest a new feature for the project.
title: "[FEAT] New Feature"
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Additional Information
      description: Provide detailed information that describes how the feature will change the current behavior.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Benefits of the Feature
      description: How will the feature benefit most, if not all, 'nyaa-watcher' users?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Code Changes
      description: Provide code changes for the feature if you have any. Use comments to specify files or context.
    validations:
      required: false